name: Publish vcpkg Binary Cache

# 手动触发
on:
  workflow_dispatch:

jobs:
  publish:
    # 最长运行 360 分钟（6 小时）
    timeout-minutes: 360
    runs-on: windows-latest

    env:
      # vcpkg 根目录
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC v142 (VS2019)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2

      - name: Clone & bootstrap vcpkg@2024.12.16
        run: |
          git clone --branch 2024.12.16 https://github.com/microsoft/vcpkg.git vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat -DisableMetrics

      - name: Install all dependencies via manifest
        run: |
          cd vcpkg
          # 自动读取仓库根目录的 vcpkg.json
          .\vcpkg.exe install --triplet x64-windows --recurse

      - name: Package vcpkg binary cache
        run: |
          cd vcpkg
          # 打包四大核心目录为 zip
          powershell -Command "Compress-Archive -Path installed,packages,buildtrees,downloads -DestinationPath ../vcpkg-cache.zip"

      - name: Create GitHub Release & upload cache
        uses: softprops/action-gh-release@v1
        with:
          tag_name: vcpkg-cache           # Release tag，可按需改
          files: vcpkg-cache.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
