# .github/workflows/publish-vcpkg-cache.yml
name: Publish vcpkg Binary Cache

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    timeout-minutes: 360
    runs-on: windows-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download existing cache (if any)
        run: |
          gh release download vcpkg-cache \
            --repo "${{ github.repository }}" \
            --pattern vcpkg-cache.zip \
            --clobber
        shell: bash
        continue-on-error: true

      - name: Extract previous cache
        shell: powershell
        run: |
          if (Test-Path vcpkg-cache.zip) {
            mkdir prev-cache
            Expand-Archive vcpkg-cache.zip -DestinationPath prev-cache -Force
          }

      - name: Setup MSVC v142 (VS2019)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2

      - name: Clone & bootstrap vcpkg@2024.12.16
        run: |
          git clone --branch 2024.12.16 https://github.com/microsoft/vcpkg.git vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat -DisableMetrics

      - name: Inject previous cache
        shell: powershell
        run: |
          if (Test-Path prev-cache\installed)  { robocopy prev-cache\installed  vcpkg\installed  /E /NJH /NJS }
          if (Test-Path prev-cache\packages)   { robocopy prev-cache\packages   vcpkg\packages   /E /NJH /NJS }
          if (Test-Path prev-cache\buildtrees) { robocopy prev-cache\buildtrees vcpkg\buildtrees /E /NJH /NJS }
          if (Test-Path prev-cache\downloads)  { robocopy prev-cache\downloads  vcpkg\downloads  /E /NJH /NJS }

      - name: Install all dependencies via manifest (incremental)
        # 切到 cmd，让 --x-install-root 语法正常
        shell: cmd
        run: |
          cd vcpkg
          .\vcpkg.exe install --x-install-root=installed --triplet x64-windows --recurse

      - name: Package vcpkg binary cache
        shell: powershell
        run: |
          cd vcpkg
          Compress-Archive -Path installed,packages,buildtrees,downloads -DestinationPath ../vcpkg-cache.zip

      - name: Create or update GitHub Release & upload cache
        uses: softprops/action-gh-release@v1
        with:
          tag_name: vcpkg-cache
          files: vcpkg-cache.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
