# .github/workflows/publish-vcpkg-cache.yml
name: Publish vcpkg Binary Cache

# 手动触发
on:
  workflow_dispatch:

# 允许读取仓库内容（Release）用于下载已有资产
permissions:
  contents: read

jobs:
  publish:
    # 最长运行 360 分钟（6 小时）
    timeout-minutes: 360
    runs-on: windows-latest

    # GH_TOKEN 让 gh CLI 自动使用 GITHUB_TOKEN 进行认证
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download existing vcpkg-cache.zip (if any)
        # 如果仓库已有 vcpkg-cache Release，则拉取 zip，否则继续
        run: |
          gh release download vcpkg-cache \
            --repo "${{ github.repository }}" \
            --pattern vcpkg-cache.zip \
            --clobber
        shell: bash
        continue-on-error: true

      - name: Extract previous cache if exists
        shell: powershell
        run: |
          if (Test-Path vcpkg-cache.zip) {
            mkdir prev-cache
            Expand-Archive vcpkg-cache.zip -DestinationPath prev-cache -Force
          }

      - name: Setup MSVC v142 (VS2019)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2

      - name: Clone & bootstrap vcpkg@2024.12.16
        run: |
          git clone --branch 2024.12.16 https://github.com/microsoft/vcpkg.git vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat -DisableMetrics

      - name: Inject previous cache into vcpkg
        shell: powershell
        run: |
          if (Test-Path prev-cache\installed)  { robocopy prev-cache\installed  vcpkg\installed  /E /NJH /NJS }
          if (Test-Path prev-cache\packages)   { robocopy prev-cache\packages   vcpkg\packages   /E /NJH /NJS }
          if (Test-Path prev-cache\buildtrees) { robocopy prev-cache\buildtrees vcpkg\buildtrees /E /NJH /NJS }
          if (Test-Path prev-cache\downloads)  { robocopy prev-cache\downloads  vcpkg\downloads  /E /NJH /NJS }

      - name: Install all dependencies via manifest (incremental)
        run: |
          cd vcpkg
          .\vcpkg.exe install \
            --x-install-root=installed \
            --triplet x64-windows \
            --recurse

      - name: Package vcpkg binary cache
        run: |
          cd vcpkg
          powershell -Command "Compress-Archive -Path installed,packages,buildtrees,downloads -DestinationPath ../vcpkg-cache.zip"

      - name: Create or update GitHub Release & upload cache
        uses: softprops/action-gh-release@v1
        with:
          tag_name: vcpkg-cache
          files: vcpkg-cache.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
